craftcms/nitro

README.md
By default `nitro add` uses `/nitro/sites` instead of `/nitro/dev`
=> Update documentation to be inline with default nitro webroot and dest

ADVANCED.md, MAILHOG.md, README.md
This adds three things:
1. Brief _Adding a Database_ section for the readme.
2. An `ADVANCED.md` markdown file that covers customizing `mysql.conf` and could be expanded to cover any other adjustments to the web server or any of its services.
3. A `MAILHOG.md` markdown file that covers MailHog setup and access. (Felt potentially long for the readme.)
Submitting as a PR in case any of this is offensive. Let me know and I can season to taste!
=> Add sections to docs

XDEBUG.md
Separated out and started with PhpStorm setup, with explicit sections for browser and console debugging. Also added hints about where to find things, and corrected the example Nitro path for accuracy.
=> Spiff up Xdebug PhpStorm setup instructions.

internal/cmd/destroy.go
When destroying the machine, Nitro would create multiple backups, all containing **all** databases.
=> Fix individual DB export on destroy

pkg/certinstall/certinstall.go
To install the Caddy Nitro root certificate on Windows hosts requires administrator privileges. The command can be run from Command Prompt, PowerShell, Windows Terminal etc, but whatever shell is used on the Windows host, it needs to be elevated.
This updates the guidance message to directly mention this to help the WSL users with the certificate install step.
=> Update WSL cert message to mention administrator rights being needed

pkg/certinstall/certinstall.go
Currently, nitro is unable to identify arch linux for installing the certificate because it does not check for this distribution name. With this change it becomes possible to initialise nitro also on arch linux.
_Without change (on arch linux):_
```
~$ NITRO_DEVELOPMENT=true nitro init
[...]
… getting Nitro’s root site certificate… ✓
Installing certificate (you might be prompted for your password)
Error: unable to find the distribution from the description: Description:       Arch Linux
```
_With change (on arch linux):_
```
~$ NITRO_DEVELOPMENT=true nitro init 
[...]
… getting Nitro’s root site certificate… ✓
Installing certificate (you might be prompted for your password)
Nitro certificates are now trusted 🔒
Nitro is ready! 🚀
```
=> Check for arch linux distribution

pkg/certinstall/certinstall.go
The certificate installation fails on Linux Mint because it is not recognized as Debian based system.
This is the ouput of the `lsb_release` command on Linux Mint 20:
=> Add Linux Mint to distro finder

command/database/import.go
After successfully importing a database dump, Nitro reports where it went and how long it took:
```
$ nitro db import dump.sql
… detecting backup type ✓
Detected postgres backup
Enter the database name: tutorial
Preparing import…
… uploading backup dump.sql ✓
Imported database "tutorial", took 4.23 seconds 💪...
```
But the `💪...` feels like it’s saying “BUT...” or preparing to say/do something else when it is in fact finished.
This PR slightly shortens that message and lets us almost literally end strong:
```
$ nitro db import dump.sql
… detecting backup type ✓
Detected postgres backup
Enter the database name: tutorial
Preparing import…
… uploading backup dump.sql ✓
Imported database "tutorial" in 4.23 seconds 💪
```
=> Omit `...` from final database import output.

command/trust/trust.go
Removes trailing ellipsis since resulting status is indicated with another character—this makes the output consistent with other commands.
**Before**
```
❯ nitro trust
… getting Nitro’s root site certificate… ✓
```
**After**
```
❯ nitro trust
… getting Nitro’s root site certificate ✓
```
=> Remove ellipsis from `nitro trust` output.

command/remove/remove.go
This makes it possible to skip the site prompt by passing an argument to `nitro remove`, consistent with other site-specific commands in the upcoming release.
**Before**
Argument still shows site prompt:
```sh
❯ nitro remove test.nitro
Select a site:
1. craftcms.nitro
2. europa.nitro
3. starterblog.nitro
4. test.nitro
5. tutorial.nitro
```
**After**
Argument skips questioning. 😎 
```sh
❯ nitro remove test.nitro
Removing test.nitro
```
=> Add site argument for `remove` command

pkg/certinstall/certinstall.go
Added a check for 'elementary' to the Debian distribution check conditional, let me know if you'd prefer if I added the full 'elementary OS' to avoid any potential conflicts!
#323
=> Add Elementary OS to certinstall conditional

command/apply/internal/match/match.go, command/apply/internal/match/match_test.go, command/context/context.go, pkg/config/config.go, pkg/config/config_test.go, pkg/prompt/prompt.go, pkg/webroot/webroot.go, pkg/webroot/webroot_test.go
We aspire to always write “web root” as two words. This intriguing PR separates them out in strings and comments without modifying variable names that’d result in a breaking change.
=> `webroot` → `web root`

install.sh
If someone runs the Nitro one-line Bash installer, the output starts with this:
```
$ bash <(curl -sLS http://installer.getnitro.sh)
Downloading package https://github.com/craftcms/nitro/releases/download/2.0.7/nitro_darwin_x86_64.tar.gz to /Users/oli/temp_nitro_extract/nitro_darwin_x86_64.tar.gz
x CHANGELOG.md
x LICENSE.md
x README.md
x nitro
Download complete.
Running with sufficient permissions to attempt to move nitro to /usr/local/bin
(... things continue to happen ...)
```
Lines like these almost look like something erroneous happened:
```
x CHANGELOG.md
```
They appear because of `tar`’s `v` flag which includes verbose output.
From [the man page](https://man7.org/linux/man-pages/man1/tar.1.html):
>       -v, --verbose
>           Verbosely list files processed.  Each instance of …
=> Reduce unarchive verbosity during install

command/alias/alias.go, pkg/validate/validate.go, pkg/validate/validate_test.go
List of hostnames for alias command can include spaces: `thisone.tld, thatone.tld`. Hostnames for other commands can't include commas. Invalid hostname: `this.tld,that.tld`.
Trying this pull request with the develop branch of nitro.
=> alias command allows spaces in list of hostnames. Different validators for hostname and list of hostnames

command/apply/apply.go, command/blackfire/off.go, command/container/new.go, command/database/add.go, command/database/import.go, command/database/new.go, command/database/remove.go, command/destroy/destroy.go, command/iniset/iniset.go, pkg/prompt/prompt.go, pkg/setup/setup.go, pkg/terminal/terminal.go
This makes several nitpicky changes to improve the clarity and consistency of some output.
- Replaces a few `...` with `…` characters for consistency.
- Prunes redundant or unnecessary words in various places.
- Fixes Blackfire “enabling” output that should be “disabling”.
- Adds a few question marks for questions, periods to finish complete statements (instead of `...`), and uses `:` for prompts that immediately list options afterward.
- Fixes several prompts to consistently display any fallback/suggestion after the complete question. (`Do a thing [Y/n]?` → `Do a thing? [Y\n]`)
Verbose, atomic commits detail each item for maximum fun.
=> Improve output

image/Dockerfile
Upgrades the `craftcms/nitro` images from buster to the new bullseye release of Debian.
=> upgrade image from buster to bullseye

command/run/run.go
With this change you could now run:
```
nitro run --image node:10 --command 'npm install --prefix /app/'
```
Note that it is optional, so if you command doesn't need flags, you can run as before, eg:
```
nitro run --image node:10 ls ./usr
```
=> Add optional --command arg

CHANGELOG.md, command/nitro/nitro.go, command/run/run.go
Adds the `run` command in Nitro which allows running any image anywhere with sensible syntax around the docker run command.
If you need to run a composer command on a host directory, not tied to an app, the `run` command could be used like so:
```bash
nitro run --image composer --interactive help
```
=> Adds the run command

command/ls/ls.go
Minor edits to shorten the help description and warm up the username+password note replacing `Note:` with a lightbulb emoji similar to how we’d style tips in READMEs and the docs. Hopefully each one is quicker to scan using a human brain.
=> Improve `ls` command wording

image/nginx/default.conf, image/nitro/security.conf
These headers are problematic for a few reasons:
- using `add_header` unconditionally means they will _always_ be added to the response. This means, eg, if Craft tries to add a `Content-Security-Policy` header, you'll end up 2 `Content-Security-Policy` headers, which results in a CORS error
- Similarly, there is no way to unset a header set by nginx when you need to, like `X-Frame-Options`
Most of these issues appear with multisite and preview, as you're dealing with multiple domains.
As a rule though, I don't think we should set any headers that _could_ be set in PHP/Craft, as it means they cannot be overridden in the response.
=> Remove aggressive headers that cannot be overridden
